CREATE TABLE [User] (
    UserID INT IDENTITY(1,1) PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Role VARCHAR(20) NOT NULL
);
CREATE TABLE Participant (
    ParticipantID INT IDENTITY(1,1) PRIMARY KEY,
    UserID INT NOT NULL,
    IDNumber VARCHAR(20),
    Phone VARCHAR(20),
FOREIGN KEY (USERID) REFERENCES[USER]
    (USERID)
    );
CREATE TABLE ORGANISER (
    ORGANISERID INT IDENTITY(1,1)PRIMARY KEY,
    USERID IN NOT NULL,
    ORGANISATIONNAME VARCHAR(150) NOT NULL,
    FOREIGN KEY (USERID) REFERENCES [USER]
    (USERID)
    );
CREATE TABLE EVENT (
    EVENTID INT IDENTITY(1,1)PRIMARY KEY,
    ORGANISERID INT NOT NULL,
    EVENTNAME VARCHAR(50) NOT NULL,
    EVENTTYPE VARCHAR(50) NOT NULL,
    EVENTDATE DATE NOT NULL,
    LOCATION VARCHAR(150) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    FOREIGN KEY (ORGANISERID) REFERENCES
    ORGANISER(ORGANISERID)
    );
