CREATE TABLE [User] (
    UserID INT IDENTITY(1,1) PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Role VARCHAR(20) NOT NULL
);
CREATE TABLE Participant (
    ParticipantID INT IDENTITY(1,1) PRIMARY KEY,
    UserID INT NOT NULL,
    IDNumber VARCHAR(20),
    Phone VARCHAR(20),
FOREIGN KEY (USERID) REFERENCES[USER]
    (USERID)
    );
CREATE TABLE ORGANISER (
    ORGANISERID INT IDENTITY(1,1)PRIMARY KEY,
    USERID IN NOT NULL,
    ORGANISATIONNAME VARCHAR(150) NOT NULL,
    FOREIGN KEY (USERID) REFERENCES [USER]
    (USERID)
    );
CREATE TABLE EVENT (
    EVENTID INT IDENTITY(1,1)PRIMARY KEY,
    ORGANISERID INT NOT NULL,
    EVENTNAME VARCHAR(50) NOT NULL,
    EVENTTYPE VARCHAR(50) NOT NULL,
    EVENTDATE DATE NOT NULL,
    LOCATION VARCHAR(150) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    FOREIGN KEY (ORGANISERID) REFERENCES
    ORGANISER(ORGANISERID)
    );
CREATE TABLE Weather (
    WeatherID INT IDENTITY(1,1) PRIMARY KEY,
    EventID INT NOT NULL,
    RecordedAt DATETIME NOT NULL,
    Temperature DECIMAL(5,2),
    Conditions VARCHAR(100),
    WindSpeed DECIMAL(5,2),
    RainProbability INT,
);
    CREATE TABLE Category (
    CategoryID INT IDENTITY(1,1) PRIMARY KEY,
    EventID INT NOT NULL,
    CategoryName VARCHAR(100) NOT NULL,
    Distance VARCHAR(50),

    FOREIGN KEY (EventID) REFERENCES Event(EventID)
);
CREATE TABLE Entry (
    EntryID INT IDENTITY(1,1) PRIMARY KEY,
    ParticipantID INT NOT NULL,
    EventID INT NOT NULL,
    CategoryID INT NOT NULL,
    EntryDate DATE NOT NULL,
    Status VARCHAR(30) NOT NULL,
FOREIGN KEY (ParticipantID) REFERENCES Participant(ParticipantID),
    FOREIGN KEY (EventID) REFERENCES Event(EventID),
    FOREIGN KEY (CategoryID) REFERENCES Category(CategoryID)
);
CREATE TABLE Route (
    RouteID INT IDENTITY(1,1) PRIMARY KEY,
    EventID INT NOT NULL,
    RouteName VARCHAR(150),
    Distance DECIMAL(6,2),
    StartPoint VARCHAR(150),
    FinishPoint VARCHAR(150),
    MapURL VARCHAR(500),

    FOREIGN KEY (EventID) REFERENCES Event(EventID)
);
CREATE TABLE Result (
    ResultID INT IDENTITY(1,1) PRIMARY KEY,
    ParticipantID INT NOT NULL,
    EventID INT NOT NULL,
    RaceNumber VARCHAR(20),
    FinishTime TIME,
    Position INT,
    Status VARCHAR(30),

    FOREIGN KEY (ParticipantID) REFERENCES Participant(ParticipantID),
    FOREIGN KEY (EventID) REFERENCES Event(EventID)
);
